[package]
name = "weaveheap-core"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"

[lib]
name = "weaveheap_core"
path = "src/lib.rs"

[dependencies]
thiserror = { workspace = true }
anyhow = { workspace = true }
