[package]
name = "weaveheap-capi"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"

[lib]
name = "weaveheap_capi"
path = "src/lib.rs"
crate-type = ["staticlib", "cdylib", "rlib"]

[dependencies]
weaveheap-core = { path = "../weaveheap-core" }
