[package]
name = "weaveheap-python"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"

[lib]
name = "weaveheap_python"
crate-type = ["cdylib"]
path = "src/lib.rs"

[dependencies]
pyo3 = { version = "0.21", features = ["extension-module"] }
weaveheap-capi = { path = "../weaveheap-capi" }
